### ISSUE TITLE
Pipeline: Setting SKIP_ACCEPTANCE_TEST doesn't skip cluster setup

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#526]
Setting `SKIP_ACCEPTANCE_TEST` in pipeline build config didn't skip the cluster setup process

[Build 1785](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/22cc5092-8304-4f17-83bf-28bf38c0a045/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south)

```
=== Executing custom script for stage 'acceptance-test' ===

You can customize this stage with the configuration script that can be viewed using the following link: 'https://github.com/WASdev/websphere-liberty-operator/blob/4e094690c56167311316bbe32e48ce271dd0943f/.one-pipeline.yaml'
For more information on custom scripts, see https://cloud.ibm.com/docs/devsecops?topic=devsecops-custom-scripts

Successfully cloned digest repo
export PEER_REVIEW_STEP_NAME="run-stage"acceptance-test
*** Acceptance test stage ***
Run common checks before testing starts
Setting up test environment
***** Enviroment setup
make: go: Command not found
./operators/scripts/installers/install-go.sh 1.21.6
2024-01-18 01:48:06 URL:https://go.dev/dl/?mode=json&include=1.21 [16549/16549] -> "-" [1]
****** Installing Go version go1.21.6 on Linux
2024-01-18 01:48:10 URL:https://dl.google.com/go/go1.21.6.linux-amd64.tar.gz [66704768/66704768] -> "-" [1]
go version go1.21.6 linux/amd64
Login Succeeded
one-pipeline Image value: [cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-20240117-1850](http://cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-20240117-1850)
one-pipeline Catalog Image value: [cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-20240117-1850](http://cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-20240117-1850)
one-pipeline Digest Value: sha256:85dba6fac2d3114da297dd78f48e517c33cf97c81c0e6cbae921b7ef6183e38b
BASE_DIR: /workspace/app/one-pipeline-config-repo
***** Cluster setup
Running [clusterWait.sh](http://clusterwait.sh/) to wait for X cluster to be provisioned
/workspace/app/one-pipeline-config-repo
Error: 'WLO_DEMAND_ID_X' was not set!
    at Object.get_env (/snapshot/pipelinectl/src/commands.ts:90:11)
    at /snapshot/pipelinectl/src/index.ts:66:20

....
....
 === Execution of custom script for stage 'acceptance-test' finished. Exit Code: '1'. ===
 ```

**Comment by idlewis** [comment]
This appears to have been fixed by other build script updates.
If SKIP_ACCEPTANCE_TEST is set then the code setup stage no longer provisions a cluster, and the acceptance test stage doesn't run at all.
